---
# These task install application

- name: update packages
  apt: upgrade=safe update_cache=yes
  sudo: True

- name: install ruby and git etc.
  apt: pkg=$item state=present
  sudo: True
  with_items:
    - gcc
    - make
    - git
    - ruby
    - rubygems
    - nodejs

- name: install gems needed
  sudo: True
  gem: name=$item state=present 
  with_items:
    - rake
    - bundler
    - dashing
    
